version: '3.8'

services:
  # Service 1: The VR-SDS Application
  web:
    build: .
    container_name: vrsds_app_container
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Wnq57177
      - DB_NAME=vrsds_enterprise
    volumes:
      - ./dataset:/app/dataset      # Sync dataset
      - ./models:/app/models        # Sync models
    networks:
      - vrsds_network

  # Service 2: The MySQL Database
  db:
    image: mysql:8.0
    container_name: vrsds_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Wnq57177
      MYSQL_DATABASE: vrsds_enterprise
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - vrsds_network

volumes:
  db_data:

networks:
  vrsds_network:
    driver: bridge